CREATE TABLE EMPLOG(
	username VARCHAR2(30),
	timestamp DATE,
	event VARCHAR2(30),
);

CREATE OR REPLACE TRIGGER track_INSERT
	BEFORE INSERT 
	ON emp
BEGIN
	INSERT INTO EMPLOG
	VALUES (USER, SYSDATE, 'BEFORE INSERT');
END;
	
CREATE OR REPLACE TRIGGER track_update
	AFTER UPDATE
	ON emp
BEGIN
	INSERT INTO EMPLOG
	VALUES (USER, SYSDATE, 'AFTER UPDATE');
END;

CREATE or REPLACE TRIGGER track_delete
	AFTER DELETE
	ON emp
BEGIN
	INSERT INTO EMPLOG
	VALUES (USER, SYSDATE, 'AFTER DELETE');
END;
